# Generated by Django 6.1.1 on 2026-09-20 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin_ean', models.CharField(max_length=13, unique=True, verbose_name='Código de Barras')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(choices=[('kg', 'Quilograma'), ('L', 'Litro'), ('un', 'Unidade')], max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(help_text='Ex: DB Ponta Negra', max_length=150)),
                ('endereco', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supermercado')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_coleta', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'unique_together': {('produto', 'filial')},
            },
        ),
    ]
