# Generated by Django 6.1.1 on 2026-09-21 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_alvo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Alvo (R$)')),
                ('email_notificacao', models.EmailField(max_length=254, verbose_name='E-mail para Aviso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Alerta Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto', verbose_name='Produto')),
            ],
        ),
    ]
