# Generated by Django 6.1.1 on 2026-09-22 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alertapreco'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrinhoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Carrinho Dinamico',
                'verbose_name_plural': 'Itens do Carrinho Dinamico',
            },
        ),
    ]
