# Generated by Django 6.1.1 on 2026-09-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemcarrinhodinamico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='gtin_ean',
            field=models.CharField(max_length=14, unique=True, verbose_name='Código de Barras'),
        ),
    ]
