# Generated by Django 6.1.1 on 2026-09-25 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_produto_gtin_ean'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaPrecoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_informado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_encontrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ean_informado', models.CharField(max_length=14)),
                ('ean_encontrado', models.CharField(blank=True, max_length=14, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('precisao_localizacao_metros', models.FloatField(blank=True, null=True)),
                ('localizacao_confirmada', models.BooleanField(default=False)),
                ('status_validacao', models.CharField(choices=[('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('nova_foto_necessaria', 'Nova foto necessária')], max_length=30)),
                ('resultado_ia', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_clientes', to='core.filial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_clientes', to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='OportunidadeEconomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_referencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('economia_unitaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('economia_percentual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_encerramento', models.CharField(blank=True, max_length=255)),
                ('evidencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidade', to='core.evidenciaprecocliente')),
            ],
        ),
    ]
